title: 'Blog by Dennis de Best'
author:
  name: 'Dennis de Best'
  email: dennis@debest.fr
taxonomies:
  - category
  - tag
metadata:
  description: 'My personal blog mainly focused on computer science, symfony, javascript, etc ...'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
